# Dockerfile for app:v1
FROM python:3.9-slim

WORKDIR /app
COPY app.py .

RUN pip install flask
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

EXPOSE 80
CMD ["python", "app.py"]

