apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chapter: istio
      topic: traffic-management
      app: app1
      version: v1
  template:
    metadata:
      name: app-pod
      labels:
        chapter: istio
        topic: traffic-management
        app: app1
        version: v1
    spec:
      containers:
        - name: app-container
          image: spatika123/app1:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    chapter: istio
    topic: traffic-management
    app: app1
    version: v1
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8080
  selector:
    chapter: istio
    topic: traffic-management
    app: app1
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      chapter: istio
      topic: traffic-management
      app: app1
      version: v2
  template:
    metadata:
      name: app2-pod
      labels:
        chapter: istio
        topic: traffic-management
        app: app1
        version: v2
    spec:
      containers:
        - name: app2-container
          image: spatika123/app1:test
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2-svc
  labels:
    chapter: istio
    topic: traffic-management
    app: app1
    version: v2
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8080
  selector:
    chapter: istio
    topic: traffic-management
    app: app1
    version: v2

