apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-ec2
spec:
  hosts:
  - "*.compute.amazonaws.com"
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: NONE

